
from SCons.Script import Command

build = 'input/build.csv'

assignment = Command('temp/assignment.csv',           # target path (output file)
        [build, 'code/stacked_did/GetSubExps.R'],  # source path (input file)
        'Rscript code/stacked_did/GetSubExps.R')   # command line string